apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: stt-fe
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - template:
        ref: stt-fe-triggertemplate
      bindings:
        - ref: stt-fe-pipeline-triggerbinding
      interceptors:
        - github:
            eventTypes: ['push']
        - cel:
            filter: "body.ref.split('/')[1] == 'heads' && body.ref.split('/')[2] == 'main'"
