apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: f7580aa1eb6f7176705176e201ecff4de93edafb
    app.openshift.io/vcs-uri: https://github.com/yasuki0707/be-stt.git
  labels:
    app: stt-be
    app.kubernetes.io/instance: stt-be
    app.kubernetes.io/name: stt-be
    app.openshift.io/runtime: js
  name: stt-be
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: stt-be
      app.kubernetes.io/name: stt-be
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: stt-be
        app.kubernetes.io/name: stt-be
    spec:
      containers:
        - env:
            - name: INGRESS_HOST
            - name: PROTOCOLS
            - name: LOG_LEVEL
              value: debug
            - name: API_KEY_STT
              valueFrom:
                secretKeyRef:
                  name: stt-api-secret
                  key: API_KEY_STT
            - name: API_ENDPOINT_STT
              valueFrom:
                secretKeyRef:
                  name: stt-api-secret
                  key: API_ENDPOINT_STT
          image: quay.io/yasuki_oshiro_ibm/be-stt
          imagePullPolicy: IfNotPresent
          # livenessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /
          #     port: 3000
          #     scheme: HTTP
          #   periodSeconds: 10
          #   successThreshold: 1
          #   timeoutSeconds: 1
          name: stt-be
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          # readinessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /
          #     port: http
          #     scheme: HTTP
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   successThreshold: 1
          #   timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: quay-io-stt-be-password
